#!/usr/bin/env bash
cd $(dirname $0)

set -ex

function dockerize {
    sed -i s/:latest/:$2/ ../dist-docker/${3}Dockerfile
    sudo docker build -t kayess/$1:$2 ../dist-docker/$3
    sudo docker push kayess/$1:$2
}

for RELEASE in precise trusty wily xenial; do
    # Make sure we have the latest source image
    for IMAGE in fost-runtime fost-builder; do
        sudo docker pull kayess/$IMAGE:$RELEASE
    done
done
