#!/usr/bin/env bash
cd $(dirname $0)

set -ex

function dockerize {
    sed -i s/:latest/:$2/ ../dist-docker/${3}Dockerfile
    sudo docker build -t kayess/$1:$2 ../dist-docker/$3
#     sudo docker push kayess/$1:$2
}

for RELEASE in trusty xenial yakkety zesty; do
    # Make sure we have the latest source image
    for IMAGE in fost-runtime fost-builder; do
        sudo docker pull kayess/$IMAGE:$RELEASE
    done

    # Get our Boost stuff in line
    rm -rf ../dist-docker
    mkdir -p ../tmp/$RELEASE
    if test -e ../tmp/$RELEASE/Boost
    then {
        pushd ../tmp/$RELEASE/Boost
        git pull origin master
    } else {
        git clone git@github.com:KayEss/fost-boost.git ../tmp/$RELEASE/Boost
        pushd ../tmp/$RELEASE/Boost
        ln ../../../../Boost/1_62_0.tar.bz2
        tar xf 1_62_0.tar.bz2
        mv boost_1_62_0 1_62_0
    }
    fi
    git submodule init
    git submodule sync --recursive
    git submodule update --init --recursive
    popd

    # Compile the code
    sudo docker run -u $(id -u):$(id -g) -it --rm=true \
        -v $(pwd)/..:/src \
        -v $(pwd)/../tmp/$RELEASE/Boost:/src/Boost/ \
        kayess/fost-builder:$RELEASE \
            bash -c -- "Boost/build 64 0 && Boost/install 64 0 && \
                PREFIX=/src/dist-docker docker/compile toolset=gcc release"
    strip ../dist-docker/bin/* ../dist-docker/lib/*

done
